name: Pact-JVM Build

on:
  push:
    branches: [ master, v4.1.x, v4.3.x, v4.4.x ]
  pull_request:
    branches: [ master, v4.1.x, v4.3.x, v4.4.x ]

jobs:
  latest_jdk:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        module: [ core, consumer, provider, pact-specification-test ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 12
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 12
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - run: ./gradlew -v
    - name: Build with Gradle
      if: runner.os != 'Windows'
      run: ./gradlew -s --no-daemon -i -p ${{ matrix.module }} clean build
    - name: Build with Gradle (Windows)
      run: gradlew -s --no-daemon -i -p ${{ matrix.module }} clean check -x :consumer:junit:clojureTest
      shell: cmd
      if: runner.os == 'Windows'

  supported_jdks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ core, consumer, provider, pact-specification-test ]
        jdk: [ 8, 9, 11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
      - run: ./gradlew -v
      - name: Build with Gradle
        run: ./gradlew -s --no-daemon -i -p ${{ matrix.module }} clean build
